### ISSUE TITLE
分享按钮不在最底层

### ISSUE THREAD

**Issue by idealclover** [xunhuweb/wechat-social-login#1]
wordpress主题中有菜单栏，当点开菜单栏的时候发现QQ分享等按钮不在最底层被遮住而是漏了出来，很难受

**Comment by xunhuweb** [comment]
自己改一下样式，如果不会，可以付费我们帮你修改






------------------
Jeff （李勇进）
Phone:+86-17898658561


重庆迅虎网络有限公司
http://www.xunhuweb.com
电话：17898658561
邮件：jeff@xunhuweb.com
QQ:6347007
wechat:leedon007
 

 
 
 
------------------ Original ------------------

**Comment by xunhuweb** [comment]
你可以关掉分享，然后用短码或php代码加到模板里面
分享图标：
php代码：<?php xh_social_loginbar();?>
短代码：[xh_social_loginbar] 






------------------
Jeff （李勇进）
Phone:+86-17898658561


重庆迅虎网络有限公司
http://www.xunhuweb.com
电话：17898658561
邮件：jeff@xunhuweb.com
QQ:6347007
wechat:leedon007
 

 
 
 
------------------ Original ------------------

**Comment by idealclover** [comment]
好的~谢谢！

 

发件人: bounces+848413-e6e6-shadowspacex=163.com@sgmail.github.com [mailto:bounces+848413-e6e6-shadowspacex=163.com@sgmail.github.com] 代表 xunhuweb
发送时间: Monday, January 29, 2018 9:08
收件人: xunhuweb/wechat-social-login <wechat-social-login@noreply.github.com>
抄送: 不蠢会死的某翠 <shadowspacex@163.com>; State change <state_change@noreply.github.com>
主题: Re: [xunhuweb/wechat-social-login] 分享按钮不在最底层 (#1)

 

你可以关掉分享，然后用短码或php代码加到模板里面 
分享图标： 
php代码：<?php xh_social_loginbar();?> 
短代码：[xh_social_loginbar] 






------------------ 
Jeff （李勇进） 
Phone:+86-17898658561 


重庆迅虎网络有限公司 
http://www.xunhuweb.com 
电话：17898658561 
邮件：jeff@xunhuweb.com <mailto:jeff@xunhuweb.com>  
QQ:6347007 
wechat:leedon007 





------------------ Original ------------------
