### ISSUE TITLE
怎么更改用户个人中心地址？

### ISSUE THREAD

**Issue by CoolRice** [xunhuweb/wechat-social-login#4]
现在点击个人中心按钮，都会调到 /wp-admin/profile，怎么更改到别的地址？

**Comment by xunhuweb** [comment]
修改登陆插件：
plugins\wechat-social-login\templates\account\login-short.php      13行






------------------
Jeff （李海峰）
Phone:+86-17898658561


重庆迅虎网络有限公司
http://www.wpweixin.net
电话：17898658561
邮件：jeff@xunhuweb.com
QQ:6347007
wechat:xunhunet
 

 
 
 
------------------ Original ------------------

**Comment by CoolRice** [comment]
@xunhuweb, 已解决，谢谢
